travis:
  secure:
    BINSTAR_TOKEN: FwZq7z6QNV78G1lTGlVA7FqRAN7NmhaqzRdnQbYtbAuxfGHeAl7BX5UC+8CEmo2rOA4QfXE73b3ArmGNHKMAGnOBypbtASPzwRUsaSiO6tYcqG2tZqKoKfzGo/fr20MjTsxBi0QkTWeh5Skh8GnWsvdpMHy/HkB/75yTiU/MNRXOtB96t4qSpkK6HDlJBkrjEwG1x0Ef+CwBQiIQV+EZIvXycx9sl97p1Olqg8b4vTdrvrbyd1nEGCnsKeRl/w7YJ1Ku7aXpt781e8whDMZEVwlzx2DEMDF6Uwx0bn+bXJB0IzeBDUkYESTZAGcA4QbfW9L4Z0EQYXhqevjw7O8xdyU1K60XSjfcVHbAvDFdjIiRSAE8UYPn5aSABWqfKQwr39xpRBBl26/0juav+7UEVftnUrHXnsvBH4uZy2o0QfC6TFStqva/9OrnbdbEipti2HYFUNKDi6v4POKmOMIWEX28H+IpA9TRHCIrRWmIRmT5EOly4LNiU0YrvxmFSVtLh/pSgP8VSelS9pDv6jqLYm1KAtmOyltv8Aw2vZspTQqLs3xucNGef7qcl3eTrbpaskSyEbaM4Tq2LmOw8WPN7cln8fmMk3YOG6fY9nV3AKRbUdiwsr1gfddsh2MVVK7PNqOBclmYTodnzzhZSSIcPcba1drRI1kq1x4iwB8Me+w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
